-- ============================================================================
-- Football Manager Sim — Turso (libSQL / SQLite-compatible) schema
-- Notes:
--   * Turso is SQLite-compatible: no native ENUM -> use TEXT + CHECK.
--   * FKs must be turned on per-connection: PRAGMA foreign_keys = ON;
--   * Multi-table trade execution is wrapped in a single transaction in
--     db/turso_client.py to keep it ACID (see execute_trade()).
-- ============================================================================

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- Users / Teams
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            TEXT PRIMARY KEY,               -- uuid
    username      TEXT UNIQUE NOT NULL,
    email         TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,                  -- pbkdf2$iterations$salt_hex$hash_hex, see db/auth.py
    created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS teams (
    id            TEXT PRIMARY KEY,               -- uuid
    manager_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    balance        INTEGER NOT NULL DEFAULT 5000000, -- in-game currency, integer cents-equivalent
    reputation    INTEGER NOT NULL DEFAULT 50,
    created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_teams_manager ON teams(manager_user_id);

-- ---------------------------------------------------------------------------
-- Players
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS players (
    id            TEXT PRIMARY KEY,               -- uuid
    name          TEXT NOT NULL,
    age           INTEGER NOT NULL CHECK (age BETWEEN 15 AND 45),
    position      TEXT NOT NULL CHECK (position IN ('GK','CB','LB','RB','DM','CM','AM','LW','RW','ST')),

    -- Core attributes (0-100 scale)
    overall       INTEGER NOT NULL CHECK (overall BETWEEN 1 AND 100),
    potential     INTEGER NOT NULL CHECK (potential BETWEEN 1 AND 100),
    consistency   INTEGER NOT NULL CHECK (consistency BETWEEN 1 AND 100), -- drives Gaussian stddev
    pace          INTEGER NOT NULL DEFAULT 50,
    finishing     INTEGER NOT NULL DEFAULT 50,
    vision        INTEGER NOT NULL DEFAULT 50,
    positioning   INTEGER NOT NULL DEFAULT 50,
    tackling      INTEGER NOT NULL DEFAULT 50,
    gk_reflexes   INTEGER NOT NULL DEFAULT 50,
    stamina       INTEGER NOT NULL DEFAULT 80,

    -- Dynamic state (updated by form/fatigue model)
    current_form  REAL NOT NULL DEFAULT 0.0,       -- rolling z-score, e.g. -2.0..+2.0
    fatigue       REAL NOT NULL DEFAULT 0.0,       -- 0 (fresh) .. 1 (exhausted)
    injury_risk   REAL NOT NULL DEFAULT 0.0,       -- 0..1, output of LSTM/1D-CNN model

    contract_years_left INTEGER NOT NULL DEFAULT 3,
    wage          INTEGER NOT NULL DEFAULT 10000,

    is_youth_product BOOLEAN NOT NULL DEFAULT 0,   -- generated by GAN/VAE academy
    generated_season  INTEGER,

    created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_players_position ON players(position);
CREATE INDEX IF NOT EXISTS idx_players_overall ON players(overall);

-- ---------------------------------------------------------------------------
-- Player Rights — decouples "who owns this player" from the player row
-- itself, and tracks buy-back / sell-on clauses independently of ownership.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player_rights (
    player_id                TEXT PRIMARY KEY REFERENCES players(id) ON DELETE CASCADE,
    owner_team_id             TEXT NOT NULL REFERENCES teams(id),

    -- Which XI slot this player currently occupies for their owning team.
    -- 'squad' = default (transfer-market owned, no specific matchday role).
    -- Set to 'starter'/'bench' by api/match_stream.py's /quick-match
    -- endpoint so a provisioned match's starting XI matches exactly what
    -- the frontend manager picked, rather than re-deriving it from overall.
    squad_role                TEXT NOT NULL DEFAULT 'squad' CHECK (squad_role IN ('starter','bench','squad')),

    -- Buy-back / recall clause (held by a PREVIOUS selling club)
    buyback_holder_team_id    TEXT REFERENCES teams(id),
    buyback_fee               INTEGER,
    buyback_expires_season    INTEGER,

    -- Sell-on percentage (owed to a previous club on the NEXT sale)
    sell_on_percentage        REAL CHECK (sell_on_percentage IS NULL OR (sell_on_percentage BETWEEN 0 AND 1)),
    sell_on_beneficiary_team_id TEXT REFERENCES teams(id),

    -- Stable link back to the frontend's client-generated player id for a
    -- *persistent* (logged-in-manager) squad. Lets api/match_stream.py's
    -- quick-match/friend-match provisioning UPDATE the same player row on
    -- every kickoff instead of INSERTing a brand-new uuid'd player each
    -- time — see _upsert_squad() in api/match_stream.py. NULL for players
    -- belonging to ephemeral guest/demo teams (no client_ref_id to key on).
    client_ref_id              TEXT,

    updated_at                TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_rights_owner ON player_rights(owner_team_id);

-- Lets _upsert_squad() find "the row I already created for this frontend
-- player id, under this team" in one query. Partial index (client_ref_id
-- IS NOT NULL) so ephemeral guest players — which never set it — don't
-- collide with each other under the same NULL value.
CREATE UNIQUE INDEX IF NOT EXISTS idx_rights_owner_clientref
    ON player_rights(owner_team_id, client_ref_id) WHERE client_ref_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Trade Negotiation State Machine
--   proposed -> countered (repeatable) -> accepted | rejected | expired | cancelled
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trade_offers (
    id             TEXT PRIMARY KEY,              -- uuid
    from_team_id   TEXT NOT NULL REFERENCES teams(id),
    to_team_id     TEXT NOT NULL REFERENCES teams(id),
    parent_offer_id TEXT REFERENCES trade_offers(id), -- set when this row is a counter-offer

    status         TEXT NOT NULL DEFAULT 'proposed'
                   CHECK (status IN ('proposed','countered','accepted','rejected','expired','cancelled')),

    -- ML anti-cheat / fairness output (see engine/market_ml.py)
    ml_fairness_score REAL,                       -- 0 (totally lopsided) .. 1 (fair)
    ml_flag        TEXT CHECK (ml_flag IN ('ok','review','blocked')) DEFAULT 'ok',

    created_at     TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at     TEXT NOT NULL,
    resolved_at    TEXT
);

CREATE INDEX IF NOT EXISTS idx_offers_teams ON trade_offers(from_team_id, to_team_id);
CREATE INDEX IF NOT EXISTS idx_offers_status ON trade_offers(status);

-- Players moving in each direction as part of an offer
CREATE TABLE IF NOT EXISTS trade_offer_players (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    offer_id      TEXT NOT NULL REFERENCES trade_offers(id) ON DELETE CASCADE,
    player_id     TEXT NOT NULL REFERENCES players(id),
    direction     TEXT NOT NULL CHECK (direction IN ('to_receiving_team','to_proposing_team'))
);

-- Cash component of an offer (either side can include cash)
CREATE TABLE IF NOT EXISTS trade_offer_cash (
    offer_id           TEXT PRIMARY KEY REFERENCES trade_offers(id) ON DELETE CASCADE,
    from_team_cash     INTEGER NOT NULL DEFAULT 0, -- proposing team pays this much
    to_team_cash       INTEGER NOT NULL DEFAULT 0   -- receiving team pays this much (rare, but supports odd swaps)
);

-- Clause terms attached to a specific player within an offer
CREATE TABLE IF NOT EXISTS trade_offer_clauses (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    offer_id              TEXT NOT NULL REFERENCES trade_offers(id) ON DELETE CASCADE,
    player_id             TEXT NOT NULL REFERENCES players(id),
    clause_type           TEXT NOT NULL CHECK (clause_type IN ('buyback','sell_on')),
    buyback_fee           INTEGER,
    buyback_expires_season INTEGER,
    sell_on_percentage    REAL CHECK (sell_on_percentage IS NULL OR (sell_on_percentage BETWEEN 0 AND 1))
);

-- ---------------------------------------------------------------------------
-- Tournaments / Matches
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tournaments (
    id           TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    stage        TEXT NOT NULL DEFAULT 'groups' CHECK (stage IN ('groups','round_of_16','quarterfinal','semifinal','final','complete')),
    starts_at    TEXT NOT NULL,
    ends_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS matches (
    id            TEXT PRIMARY KEY,
    tournament_id TEXT REFERENCES tournaments(id),
    home_team_id  TEXT NOT NULL REFERENCES teams(id),
    away_team_id  TEXT NOT NULL REFERENCES teams(id),
    stage         TEXT NOT NULL DEFAULT 'group',
    scheduled_at  TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','live','completed','cancelled')),

    home_score    INTEGER DEFAULT 0,
    away_score    INTEGER DEFAULT 0,
    home_xg       REAL DEFAULT 0,
    away_xg       REAL DEFAULT 0,

    -- seed persisted so a match replay is byte-for-byte reproducible
    rng_seed      INTEGER,

    -- Set when a friend-match ends because one side's socket never came
    -- back within the grace period (see _handle_side_disconnect in
    -- api/match_stream.py) rather than by reaching full_time normally.
    -- status still resolves to 'completed' (walkover) so downstream
    -- reporting doesn't need a new status value; this column is what
    -- distinguishes "won 3-0 by forfeit" from "won 3-0 on the pitch".
    forfeited_side TEXT CHECK (forfeited_side IN ('home','away')),

    created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_matches_tournament ON matches(tournament_id, scheduled_at);

CREATE TABLE IF NOT EXISTS match_events (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    match_id       TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    minute         INTEGER NOT NULL,
    event_type     TEXT NOT NULL, -- 'chance','shot','goal','save','chaos','substitution','card', etc.
    team_id        TEXT REFERENCES teams(id),
    player_id      TEXT REFERENCES players(id),
    description    TEXT NOT NULL,
    momentum_home  REAL,
    momentum_away  REAL,
    created_at     TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_events_match ON match_events(match_id, minute);

-- ---------------------------------------------------------------------------
-- Player form/fatigue history (feeds the time-series forecasting model)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player_form_history (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    player_id       TEXT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    match_id        TEXT REFERENCES matches(id),
    minutes_played  INTEGER NOT NULL DEFAULT 0,
    match_rating    REAL,               -- 0-10 rating produced by the match engine
    fatigue_after   REAL,
    recorded_at     TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_form_player ON player_form_history(player_id, recorded_at);
